spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lab:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
  datasource:
    username: postgres
    password: -R[D+d)<6HKQ)_\T
  cloud:
    gcp:
      project-id: recipe-app-354019
      sql:
        enabled: true
        database-name: recipeapp
        instance-connection-name: recipe-app-354019:us-central1:recipe-app-db
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}